name = "mate-music-search"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "mate-music-db"
database_id = "placeholder"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "mate-music-db"
database_id = "placeholder"

[env.preview]
vars = { NODE_ENV = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "mate-music-db"
database_id = "placeholder"
